spring.application.name=social-fetchReel

# JWT

spring.jwt.secret=${JWT_SECRET}

# Internal Service Secret

secret.service=${SERVICE_SECRET}

# Internal Services

reel.uri=http://reel-service:8084
interest.uri=http://interest-service:8088

# Health

health.uri=http://reelfetch-service:8089/api/health

# Server

server.port=8089

# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example.social_fetchReels=INFO
logging.level.org.springframework=INFO

# Actuator

management.endpoint.health.show-details=always
management.datadog.metrics.export.enabled=true
management.defaults.metrics.export.enabled=true

management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true

management.endpoint.web.base-path=/actuator
management.endpoints.web.exposure.include=*
9