spring.application.name=social-fetchReel

service.secret.gateway= ${GATEWAY_SECRET}

# Internal Service Secret

secret.service=${SERVICE_SECRET}

# Internal Services

reel.uri=http://reel-service:8084
interest.uri=http://interest-service:8088

# Health

health.uri=http://reelfetch-service:8089/api/health

# Server

server.port=8089
# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example.social_likes=INFO
logging.level.org.springframework=INFO


management.datadog.metrics.export.enabled=true


management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces

# Enforce W3C Trace Context headers (Gateway and services must match)
management.tracing.propagation.type=w3c

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=reelFetch-service

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG