global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8080'

  # Profile Service
  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'profile-service:8081'

  # Post Service
  - job_name: 'post-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'post-service:8082'

  # Likes Service
  - job_name: 'likes-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'likes-service:8083'

  # Reel Service
  - job_name: 'reel-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'reel-service:8084'

  # Interaction Service
  - job_name: 'interaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'interaction-service:8085'

  # Feed Service
  - job_name: 'feed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'feed-service:8086'

  # View Service
  - job_name: 'view-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'view-service:8087'

  # Interest Service
  - job_name: 'interest-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'interest-service:8088'

  # Reel Fetch Service
  - job_name: 'reelfetch-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'reelfetch-service:8089'

  # Chat Service
  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'chat-service:8090'

  # API Gateway
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway:8091'