spring.application.name=auth-social

# Retry

resilience4j.retry.instances.importantApi.max-attempts=3
resilience4j.retry.instances.importantApi.wait-duration=2s
resilience4j.retry.instances.importantApi.enable-exponential-backoff=true
resilience4j.retry.instances.importantApi.exponential-backoff-multiplier=2
resilience4j.retry.instances.importantApi.retry-exceptions=\
java.net.ConnectException,\
java.net.SocketTimeoutException,\
feign.RetryableException

# Circuit Breaker

resilience4j.circuitbreaker.instances.importantApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.importantApi.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.importantApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.importantApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.importantApi.permitted-number-of-calls-in-half-open-state=3

# Database

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# JPA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.port=${PORT:8080}

# Internal Services

service.secret=${SERVICE_SECRET}
profile.service.url=${PROFILE_SERVICE_URL}

# JWT

jwt.secret=${JWT_SECRET}

# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example.auth-social=INFO
logging.level.org.springframework=INFO

# Metrics

management.endpoint.health.show-details=always
management.defaults.metrics.export.enabled=true
management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true
management.endpoint.web.base-path=/actuator
management.endpoints.web.exposure.include=*
