spring.application.name=social_interest

# MongoDB

spring.data.mongodb.uri=${MONGO_URI}

# Internal Service Secret

secret.service=${SERVICE_SECRET}

# Health

health.uri=http://interest-service:8088/api/health

# Server

server.port=8088

# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example.social_interest=INFO
logging.level.org.springframework=INFO

management.datadog.metrics.export.enabled=true


# Actuator / Metrics

management.defaults.metrics.export.enabled=true
management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true
management.endpoint.web.base-path=/actuator

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces

# Enforce W3C Trace Context headers (Gateway and services must match)
management.tracing.propagation.type=w3c

app.gateway.secret= ${APP_GATEWAY_SECRET}
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=interest-service

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

