spring.application.name=social-post

# Retry

resilience4j.retry.instances.importantApi.max-attempts=3
resilience4j.retry.instances.importantApi.wait-duration=2s
resilience4j.retry.instances.importantApi.enable-exponential-backoff=true
resilience4j.retry.instances.importantApi.exponential-backoff-multiplier=2
resilience4j.retry.instances.importantApi.retry-exceptions=\
java.net.ConnectException,\
java.net.SocketTimeoutException,\
feign.RetryableException

# Circuit Breaker

resilience4j.circuitbreaker.instances.importantApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.importantApi.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.importantApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.importantApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.importantApi.permitted-number-of-calls-in-half-open-state=3

# Cloudflare R2

cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.bucket=posts
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.posts-public-url=${R2_POSTS_PUBLIC_URL}

# MongoDB

spring.data.mongodb.uri=${MONGO_URI}

# Security

spring.jwt.secret=${JWT_SECRET}
service.secret=${SERVICE_SECRET}

# Logging

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example=INFO

# Internal Services

ping.uri=http://post-service:8082/api/health
post.uri=http://feed-service:8086
profile.uri=http://profile-service:8081
like.url=http://likes-service:8083
feed.url=http://feed-service:8086

# Server

server.port=8082

# CORS

app.cors.allowed-origins=*

# Multipart Uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Actuator / Metrics

management.endpoint.health.show-details=always
management.defaults.metrics.export.enabled=true
management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true
management.endpoint.web.base-path=/actuator
management.endpoints.web.exposure.include=*
