spring.application.name=Friend_Feed

# Retry

resilience4j.retry.instances.importantApi.max-attempts=3
resilience4j.retry.instances.importantApi.wait-duration=2s
resilience4j.retry.instances.importantApi.enable-exponential-backoff=true
resilience4j.retry.instances.importantApi.exponential-backoff-multiplier=2

resilience4j.retry.instances.importantApi.retry-exceptions=\
java.net.ConnectException,\
java.net.SocketTimeoutException,\
feign.RetryableException

# Circuit Breaker

resilience4j.circuitbreaker.instances.importantApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.importantApi.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.importantApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.importantApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.importantApi.permitted-number-of-calls-in-half-open-state=3

# JWT

spring.jwt.secret=${JWT_SECRET}

# MongoDB

spring.data.mongodb.uri=${MONGO_URI}

# Internal Service Secret

service.secret=${SERVICE_SECRET}

# Internal Services

post.uri=http://post-service:8082
interaction.uri=http://interaction-service:8085
likes.uri=http://likes-service:8083

# Health

ping.url=http://feed-service:8086/api/health

# Server

server.port=8086

# Logging

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.com.example.Friend_Feed=INFO
logging.level.org.springframework=INFO

# Actuator

management.endpoint.health.show-details=always
management.datadog.metrics.export.enabled=true
management.defaults.metrics.export.enabled=true

management.metrics.use-global-registry=true
management.endpoint.metrics.enabled=true

management.endpoint.web.base-path=/actuator
management.endpoints.web.exposure.include=*
